--------------------------------------------------------
--  File created - Saturday-January-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_NURSING_HOME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN_NURSING_HOME" 
   (	"ADMIN_USER_ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADMIN_NURSING_HOME
SET DEFINE OFF;
Insert into SYSTEM.ADMIN_NURSING_HOME (ADMIN_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a1','j#5gHW~]Z''2Q2g?u','E1');
Insert into SYSTEM.ADMIN_NURSING_HOME (ADMIN_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a2','c~d@,mK&2r5gF$v(','E2');
Insert into SYSTEM.ADMIN_NURSING_HOME (ADMIN_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a10','Twx-=af2>N4)G=5g','E10');
Insert into SYSTEM.ADMIN_NURSING_HOME (ADMIN_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a11',';NJQ8Pj"Y?Jy9+\2','E11');
--------------------------------------------------------
--  DDL for Index ADMIN_NURSING_HOME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADMIN_NURSING_HOME_PK" ON "SYSTEM"."ADMIN_NURSING_HOME" ("ADMIN_USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMIN_NURSING_HOME" ADD CONSTRAINT "ADMIN_NURSING_HOME_PK" PRIMARY KEY ("ADMIN_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ADMIN_NURSING_HOME" MODIFY ("ADMIN_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADMIN_NURSING_HOME" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADMIN_NURSING_HOME" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADMIN_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMIN_NURSING_HOME" ADD CONSTRAINT "FK_ADMIN_EMPLOYEE_ID" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "SYSTEM"."EMPLOYEE_NURSING_HOME" ("EMPLOYEE_ID") ENABLE;
