--------------------------------------------------------
--  File created - Saturday-January-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOCTOR_NURSING_HOME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DOCTOR_NURSING_HOME" 
   (	"DOCTOR_USER_ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.DOCTOR_NURSING_HOME
SET DEFINE OFF;
Insert into SYSTEM.DOCTOR_NURSING_HOME (DOCTOR_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a5',';V{xtT!Ahd4PYCKg','E5');
Insert into SYSTEM.DOCTOR_NURSING_HOME (DOCTOR_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a6','?n?@mk>\3T8<.BQ:','E6');
Insert into SYSTEM.DOCTOR_NURSING_HOME (DOCTOR_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a14','Ps[nt>\ZF8Zs''6%a','E14');
Insert into SYSTEM.DOCTOR_NURSING_HOME (DOCTOR_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a15','G<zhRU{Qm9+C#$Jz','E15');
Insert into SYSTEM.DOCTOR_NURSING_HOME (DOCTOR_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a21','b[mV-uDE?V/nTj34','E21');
Insert into SYSTEM.DOCTOR_NURSING_HOME (DOCTOR_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a22','jWVuM`AC((;6jpuW','E22');
--------------------------------------------------------
--  DDL for Index DOCTOR_NURSING_HOME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DOCTOR_NURSING_HOME_PK" ON "SYSTEM"."DOCTOR_NURSING_HOME" ("DOCTOR_USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DOCTOR_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DOCTOR_NURSING_HOME" ADD CONSTRAINT "DOCTOR_NURSING_HOME_PK" PRIMARY KEY ("DOCTOR_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."DOCTOR_NURSING_HOME" MODIFY ("DOCTOR_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DOCTOR_NURSING_HOME" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DOCTOR_NURSING_HOME" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DOCTOR_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DOCTOR_NURSING_HOME" ADD CONSTRAINT "FK_DOCTOR_EMPLOYEE_ID" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "SYSTEM"."EMPLOYEE_NURSING_HOME" ("EMPLOYEE_ID") ENABLE;
