--------------------------------------------------------
--  File created - Saturday-January-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE_NURSING_HOME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" 
   (	"EMPLOYEE_ID" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"CNO" NUMBER(*,0), 
	"GENDER" CHAR(1 BYTE), 
	"QUALIFICATION" VARCHAR2(20 BYTE), 
	"SPECALIZATION" VARCHAR2(20 BYTE), 
	"SHIFT" CHAR(1 BYTE), 
	"HIREDATE" DATE, 
	"SALARY" FLOAT(126), 
	"POSITION" VARCHAR2(20 BYTE), 
	"UNIQUE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLOYEE_NURSING_HOME
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E1','Adam','A','Lee','9223 Acacia St.',4178807020,'M','PHD',null,'D',to_date('11-JAN-16','DD-MON-RR'),450000,'ADMIN','a1');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E2','Abela','A','Ford','9884 S. Brookside Street',6295620979,'F','MTECH',null,'N',to_date('09-MAY-14','DD-MON-RR'),550000,'ADMIN','a2');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E3','Becky','B','Williams','2 W. Union St.',8066033945,'F','MBA','IM','D',to_date('12-JUN-15','DD-MON-RR'),500000,'ACCOUNTANT','a3');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E4','Barb','D','Beiber','64 Laurel Dr.',3577403165,'M','MBA','ACCOUNTS','D',to_date('04-MAY-13','DD-MON-RR'),350000,'ACCOUNTANT','a4');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E5','Debbie','G','Floydd','939 Pilgrim St.',4615606568,'F','MBBS','ENT','N',to_date('12-NOV-17','DD-MON-RR'),750000,'DOCTOR','a5');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E6','Dean','E','Strong','8036 Sutor Ave.',6923902153,'M','MBBS','Ortholyrnxgology','D',to_date('06-MAY-15','DD-MON-RR'),850000,'DOCTOR','a6');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E7','Natasha','Y','Yang','8665 Colonial Ave.',5132577303,'F','MSC','Hospitality','W',to_date('15-FEB-13','DD-MON-RR'),270000,'NURSE','a7');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E8','Natalie','E','Portman','239 Leeton Ridge Drive',9849013100,'F','MSC','Hospitality','W',to_date('09-JAN-17','DD-MON-RR'),220000,'NURSE','a8');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E9','Rita','W','Gilbert','60 Addison St.',4329772568,'F','DIPLOMA',null,'W',to_date('13-FEB-12','DD-MON-RR'),200000,'RECEPTIONIST','a9');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E10','Ryan','K','Neal','61 Surrey Court',6828976103,'M','PHD',null,'D',to_date('11-JAN-16','DD-MON-RR'),450000,'ADMIN','a10');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E11','Kenneth','T','Gardner','8231 Shub Farm Avenue',6385223916,'F','MTECH',null,'N',to_date('09-MAY-14','DD-MON-RR'),550000,'ADMIN','a11');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E12','Jeremiah','G','Wheeler','78 W. Mammoth St.',8649837567,'F','MBA','IM','D',to_date('12-JUN-15','DD-MON-RR'),500000,'ACCOUNTANT','a12');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E13','Peter','D','Woods','8386 Gulf Street',9937143831,'M','MBA','ACCOUNTS','D',to_date('04-MAY-13','DD-MON-RR'),350000,'ACCOUNTANT','a13');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E14','Rex','G','Blake','376 Mountainview Drive',4725124697,'F','MBBS','ENT','N',to_date('12-NOV-17','DD-MON-RR'),750000,'DOCTOR','a14');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E15','Ebony','Y','Cox','979 Lancaster Street',9156981309,'M','MBBS','Ortholyrnxgology','D',to_date('06-MAY-15','DD-MON-RR'),850000,'DOCTOR','a15');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E16','Randy','B','Knight','9 South Virginia Street',8716065492,'F','MSC','Hospitality','W',to_date('15-FEB-13','DD-MON-RR'),270000,'NURSE','a16');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E17','Dianna','C','Perry','69 Deerfield Rd.',4838804314,'F','BSC','Hospitality','W',to_date('09-JAN-17','DD-MON-RR'),220000,'NURSE','a17');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E18','Dallas','J','Burns','28 Rockville Road',6328481605,'F','DIPLOMA',null,'W',to_date('13-FEB-12','DD-MON-RR'),200000,'RECEPTIONIST','a18');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E19','Wilson','I','Estrada','55 East Halifax Street',4936192417,'M','MBA',null,'D',to_date('12-JUN-15','DD-MON-RR'),500000,'ACCOUNTANT','a19');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E20','Pat','Q','Summers','15 Brewery Ave.',5108038707,'F','MBA','IM','D',to_date('04-MAY-13','DD-MON-RR'),350000,'ACCOUNTANT','a20');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E21','Leroy','O','Phillips','9267 Cedar Court',7179077089,'M','MBA','ACCOUNTS','N',to_date('12-NOV-17','DD-MON-RR'),750000,'DOCTOR','a21');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E22','Winston','A','Watkins','256 Nicolls Street',8514525843,'F','MBBS','ENT','D',to_date('06-MAY-15','DD-MON-RR'),850000,'DOCTOR','a22');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E23','Pat','L','Brewer','469 Shipley Ave.',6912253350,'F','MBBS','Ortholyrnxgology','W',to_date('15-FEB-13','DD-MON-RR'),270000,'NURSE','a23');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E24','Kelley','V','Bowman','537 Lakeview St.',3612084512,'F','BSC','Hospitality','W',to_date('09-JAN-17','DD-MON-RR'),220000,'NURSE','a24');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E25','Jenna','W','Rhodes','654 Second Court',4282795862,'M','DIPLOMA','Hospitality','W',to_date('13-FEB-12','DD-MON-RR'),200000,'RECEPTIONIST','a25');
--------------------------------------------------------
--  DDL for Index EMPLOYEE_NURSING_HOME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYEE_NURSING_HOME_PK" ON "SYSTEM"."EMPLOYEE_NURSING_HOME" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" ADD CONSTRAINT "EMPLOYEE_NURSING_HOME_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("FNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("MNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("LNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("CNO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("HIREDATE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("SALARY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("POSITION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("UNIQUE_ID" NOT NULL ENABLE);
