--------------------------------------------------------
--  File created - Friday-January-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE_NURSING_HOME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" 
   (	"EMPLOYEE_ID" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"CNO" NUMBER(*,0), 
	"GENDER" CHAR(1 BYTE), 
	"QUALIFICATION" VARCHAR2(20 BYTE), 
	"SPECALIZATION" VARCHAR2(20 BYTE), 
	"SHIFT" CHAR(1 BYTE), 
	"HIREDATE" DATE, 
	"SALARY" FLOAT(126), 
	"POSITION" VARCHAR2(20 BYTE), 
	"UNIQUE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLOYEE_NURSING_HOME
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E1','adam','a','admin','becker st',9854732160,'M','PHD',null,'D',to_date('11-JAN-16','DD-MON-RR'),450000,'ADMIN','a1');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E2','abela','a','admin','dock avenue',9548763210,'F','MTECH',null,'N',to_date('09-MAY-14','DD-MON-RR'),550000,'ADMIN','a2');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E3','becky','b','acnt','morning bay',7854120254,'F','MBA','IM','D',to_date('12-JUN-15','DD-MON-RR'),500000,'ACCOUNTANT','a3');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E4','barb','b','jr','nightangle',7458401134,'M','MBA','ACCOUNTAN','D',to_date('04-MAY-13','DD-MON-RR'),350000,'ACCOUNTANT','a4');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E5','debbie','d','floyd','maven st',8541724582,'F','MBBS','ENT','N',to_date('12-NOV-17','DD-MON-RR'),750000,'DOCTOR','a5');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E6','dean','w','stalion','superst',9114523687,'M','MBBS','Neuro','D',to_date('06-MAY-15','DD-MON-RR'),850000,'DOCTOR','a6');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E7','natasha','v','romanoff','avengers',855597770,'F','MSC','Hospitality','W',to_date('15-FEB-13','DD-MON-RR'),270000,'NURSE','a7');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E8','natalie','b','damon','vita',4123456742,'F','MSC','Hospitality','W',to_date('09-JAN-17','DD-MON-RR'),220000,'NURSE','a8');
Insert into SYSTEM.EMPLOYEE_NURSING_HOME (EMPLOYEE_ID,FNAME,MNAME,LNAME,ADDRESS,CNO,GENDER,QUALIFICATION,SPECALIZATION,SHIFT,HIREDATE,SALARY,POSITION,UNIQUE_ID) values ('E9','rita','j','johaness','beverly',9658120433,'F','diploma',null,'W',to_date('13-FEB-12','DD-MON-RR'),200000,'RECEPTIONIST','a9');
--------------------------------------------------------
--  DDL for Index EMPLOYEE_NURSING_HOME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYEE_NURSING_HOME_PK" ON "SYSTEM"."EMPLOYEE_NURSING_HOME" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" ADD CONSTRAINT "EMPLOYEE_NURSING_HOME_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("FNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("MNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("LNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("CNO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("HIREDATE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("SALARY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("POSITION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE_NURSING_HOME" MODIFY ("UNIQUE_ID" NOT NULL ENABLE);
