--------------------------------------------------------
--  File created - Saturday-January-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NURSE_NURSING_HOME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NURSE_NURSING_HOME" 
   (	"NURSE_USER_ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.NURSE_NURSING_HOME
SET DEFINE OFF;
Insert into SYSTEM.NURSE_NURSING_HOME (NURSE_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a7','b56x>f;~7}~MS(MC','E7');
Insert into SYSTEM.NURSE_NURSING_HOME (NURSE_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a8','{5<D(r:7C*/G9rc@','E8');
Insert into SYSTEM.NURSE_NURSING_HOME (NURSE_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a16','},[7md*R$:MrQ:Jy','E16');
Insert into SYSTEM.NURSE_NURSING_HOME (NURSE_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a17','N+\c`<JhDPs9y-;y','E17');
Insert into SYSTEM.NURSE_NURSING_HOME (NURSE_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a23','=M%R/X8Y$bg*SAqe','E23');
Insert into SYSTEM.NURSE_NURSING_HOME (NURSE_USER_ID,PASSWORD,EMPLOYEE_ID) values ('a24','f,EG*WT2u=`CG_<v','E24');
--------------------------------------------------------
--  DDL for Index NURSE_NURSING_HOME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NURSE_NURSING_HOME_PK" ON "SYSTEM"."NURSE_NURSING_HOME" ("NURSE_USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NURSE_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NURSE_NURSING_HOME" ADD CONSTRAINT "NURSE_NURSING_HOME_PK" PRIMARY KEY ("NURSE_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."NURSE_NURSING_HOME" MODIFY ("NURSE_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."NURSE_NURSING_HOME" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."NURSE_NURSING_HOME" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NURSE_NURSING_HOME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NURSE_NURSING_HOME" ADD CONSTRAINT "FK_NURSE_EMPLOYEEID" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "SYSTEM"."EMPLOYEE_NURSING_HOME" ("EMPLOYEE_ID") ENABLE;
