--------------------------------------------------------
--  File created - Friday-January-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTGUARDIANINFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PATIENTGUARDIANINFO" 
   (	"GNAME" VARCHAR2(20 BYTE), 
	"MOTHERNAME" VARCHAR2(20 BYTE), 
	"FATHERNAME" VARCHAR2(20 BYTE), 
	"GUARDIANID" VARCHAR2(20 BYTE), 
	"PATIENTID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PATIENTGUARDIANINFO
SET DEFINE OFF;
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Kadeem','Adena','Sebastian','100','5000');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Norman','Carol','Chadwick','101','5001');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Garett','Alyssa','Austin','102','5002');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Steven','Germaine','Tyrone','103','5003');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Hammmett','Brittany','Uriah','104','5004');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Yeo','Adele','Beck','105','5005');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Tatyana','Selma','Hedley','106','5006');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Driscoll','Samantha','Blake','107','5007');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Ivy','Sybil','Conan','108','5008');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Cantha','Melissa','Brody','109','5009');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Cora','Mona','Wang','110','5010');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Sydeny','Lucy','Lane','111','5011');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Lana','Wilma','Bert','112','5012');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Michelle','Rinah','Berk','113','5013');
Insert into SYSTEM.PATIENTGUARDIANINFO (GNAME,MOTHERNAME,FATHERNAME,GUARDIANID,PATIENTID) values ('Zoe','Cassadiy','Troy','114','5014');
--------------------------------------------------------
--  DDL for Index PK_GUARDIANID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_GUARDIANID" ON "SYSTEM"."PATIENTGUARDIANINFO" ("GUARDIANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENTGUARDIANINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" ADD CONSTRAINT "PK_GUARDIANID" PRIMARY KEY ("GUARDIANID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" MODIFY ("GNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" MODIFY ("MOTHERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" MODIFY ("FATHERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" MODIFY ("GUARDIANID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" MODIFY ("PATIENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PATIENTGUARDIANINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTGUARDIANINFO" ADD CONSTRAINT "PATIENTID" FOREIGN KEY ("PATIENTID")
	  REFERENCES "SYSTEM"."PATIENTPERSONALINFO" ("PATIENTID") ENABLE;
