--------------------------------------------------------
--  File created - Friday-January-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTCONTACTDETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PATIENTCONTACTDETAILS" 
   (	"PATIENTID" VARCHAR2(20 BYTE), 
	"MOBILENO" NUMBER, 
	"LANDLINENO" NUMBER, 
	"EMAIL" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PATIENTCONTACTDETAILS
SET DEFINE OFF;
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5000',4467626463,null,'5vlady.vld.37w@gseevqvve.shop');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5001',3496142826,null,'o06170954@stormgain.net');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5003',6391205939,null,'0mocor.h@qtvpatxl.shop');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5004',5627408815,null,'dmr.kimo7079@partidecitoyens.org');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5005',3443140568,null,'vdriss-fa@super-date-now3.com');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5006',6908070018,null,'gdjalilhos@pusakaqq.org');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5007',1536467082,null,'njcychi@u6yksh-mail.xyz');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5008',9934547168,null,'eyassin-ochriffv@¿¿¿¿¿¿¿.¿¿');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5009',4212277417,null,'4eliz@agentoto4d.org');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5010',4212277418,null,'mali.hus@pokersbo338.org');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5011',6417963421,null,'9alkhawldav@qtvpatxl.shop');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5012',9272436667,null,'qasaad.kh@eventao.com');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5013',7378877300,null,'9corly6@uj0sx.info');
Insert into SYSTEM.PATIENTCONTACTDETAILS (PATIENTID,MOBILENO,LANDLINENO,EMAIL) values ('5014',2967534356,null,'9hajajmed2@nekopoker.net');
--------------------------------------------------------
--  DDL for Index PK_CONTACT_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CONTACT_EMAIL" ON "SYSTEM"."PATIENTCONTACTDETAILS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENTCONTACTDETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTCONTACTDETAILS" ADD CONSTRAINT "PK_CONTACT_EMAIL" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PATIENTCONTACTDETAILS" MODIFY ("PATIENTID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTCONTACTDETAILS" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PATIENTCONTACTDETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTCONTACTDETAILS" ADD CONSTRAINT "FK_CONTACTDETAILS_PATIENTID" FOREIGN KEY ("PATIENTID")
	  REFERENCES "SYSTEM"."PATIENTPERSONALINFO" ("PATIENTID") ENABLE;
