--------------------------------------------------------
--  File created - Friday-January-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTOTHERDETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PATIENTOTHERDETAILS" 
   (	"ODETAILSID" VARCHAR2(20 BYTE), 
	"NATIONALITY" VARCHAR2(20 BYTE), 
	"RELIGION" VARCHAR2(20 BYTE), 
	"OCCUPATION" VARCHAR2(20 BYTE), 
	"INCOME" FLOAT(126), 
	"VIP" CHAR(1 BYTE), 
	"PATIENTID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PATIENTOTHERDETAILS
SET DEFINE OFF;
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('701','US','Christian','Manager',45000,'N','5000');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('702','US','Jew','Lawyer',25000,'N','5001');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('703','US','Christian','Manager',55000,'N','5002');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('704','US','Christian','Artist',20000,'N','5003');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('705','US','Jew','Manager',84000,'N','5004');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('706','US','Jew','Lawyer',43000,'N','5005');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('707','US','Christian','Model',120000,'Y','5006');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('708','US','Jew','CEO',540000,'Y','5007');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('709','US','Christian','Artist',256000,'N','5008');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('710','US','Jew','Lawyer',98000,'N','5009');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('711','US','Christian','FireFighter',35400,'Y','5010');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('712','US','Christian','Manager',85420,'N','5011');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('713','US','Jew','Cricketer',100000,'Y','5012');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('714','US','Christian','StockBroker',150000,'Y','5013');
Insert into SYSTEM.PATIENTOTHERDETAILS (ODETAILSID,NATIONALITY,RELIGION,OCCUPATION,INCOME,VIP,PATIENTID) values ('715','US','Christian','Freelancer',80000,'N','5014');
--------------------------------------------------------
--  DDL for Index PATIENTOTHERDETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PATIENTOTHERDETAILS_PK" ON "SYSTEM"."PATIENTOTHERDETAILS" ("ODETAILSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENTOTHERDETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" ADD CONSTRAINT "PATIENTOTHERDETAILS_PK" PRIMARY KEY ("ODETAILSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("ODETAILSID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("NATIONALITY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("RELIGION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("OCCUPATION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("INCOME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("VIP" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" MODIFY ("PATIENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PATIENTOTHERDETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTOTHERDETAILS" ADD CONSTRAINT "FK_OTHER_PATIENT" FOREIGN KEY ("PATIENTID")
	  REFERENCES "SYSTEM"."PATIENTPERSONALINFO" ("PATIENTID") ENABLE;
