--------------------------------------------------------
--  File created - Friday-January-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTADDRESSDETAILS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PATIENTADDRESSDETAILS" 
   (	"CONTACTID" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(*,0), 
	"PATIENTID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PATIENTADDRESSDETAILS
SET DEFINE OFF;
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('200','162 Nec, Avenue','USA','IL','Elgin',60120,'5000');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('201','Ap #461-5892 At St.','USA','TX','Austin',78746,'5001');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('203','3168 Nam Rd.','USA','PA','Philadelphia',19103,'5003');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('204','654-6530 Mauris St.','USA','SC','Winnsborg',29810,'5004');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('205','144-697 Tempus Rd.','USA','CA','Redding',96002,'5005');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('206','324-89 Compton','USA','UT','Providence',23410,'5006');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('207','Ap #425-9686Avenue','USA','TX','Salt Lake',84111,'5007');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('208','5355 Bibendum. Road','USA','FL','Vidor',77662,'5008');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('209','992-8753 Magna Rd.','USA','NC','St Petersen',33701,'5009');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('210','948-9873 Ad Street','USA','SC','Jackson',28546,'5010');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('211','2913 Egestas St.','USA','CT','North Austin',29841,'5011');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('212','9148 Tempus, Av.','USA','VT','Wallingfort',6492,'5012');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('213','4153 Tempus Rd.','USA','IN','Island Palma',5846,'5013');
Insert into SYSTEM.PATIENTADDRESSDETAILS (CONTACTID,ADDRESS,COUNTRY,STATE,CITY,PINCODE,PATIENTID) values ('214','2119 Interdum Ave','USA','VA','Huntingturf',46570,'5014');
--------------------------------------------------------
--  DDL for Index PATIENTCONTACTDETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PATIENTCONTACTDETAILS_PK" ON "SYSTEM"."PATIENTADDRESSDETAILS" ("CONTACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENTADDRESSDETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" ADD CONSTRAINT "PATIENTCONTACTDETAILS_PK" PRIMARY KEY ("CONTACTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("CONTACTID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("COUNTRY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("STATE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("PINCODE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" MODIFY ("PATIENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PATIENTADDRESSDETAILS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENTADDRESSDETAILS" ADD CONSTRAINT "FK_CONTACT_PATIENTID" FOREIGN KEY ("PATIENTID")
	  REFERENCES "SYSTEM"."PATIENTPERSONALINFO" ("PATIENTID") ENABLE;
